window.SCHOOLS_FYI_DATA = {
  grades: ["JK", "SK", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
  subjects: ["Math", "Language"],
  providers: [
    { id:"ontario", name:"Ontario Curriculum", short:"ON", kind:"curriculum", badge:"Provincial standard", color:"green", range:"JK–12", default:true, url:"https://www.dcp.edu.gov.on.ca/en/curriculum/", summary:{Math:"Province-wide expectations organized by grade, with strands that develop mathematical knowledge, skills, and problem solving.",Language:"Province-wide expectations for literacy learning, including reading, writing, oral communication, and media literacy."}, native:"Ontario grade" },
    { id:"ap", name:"Advanced Placement", short:"AP", kind:"curriculum", badge:"Standardized program", color:"blue", range:"Secondary courses", url:"https://apstudents.collegeboard.org/course-index-page", summary:{Math:"Course-specific, college-level pathways such as calculus and statistics; availability and prerequisites are set by each school.",Language:"Course-specific, college-level English language and literature study rather than a full JK–12 sequence."}, native:"AP course", secondaryOnly:true },
    { id:"ib", name:"International Baccalaureate", short:"IB", kind:"curriculum", badge:"Standardized program", color:"navy", range:"Ages 3–19", url:"https://www.ibo.org/programmes/", summary:{Math:"Inquiry-led mathematics across IB programmes, culminating in distinct Diploma Programme course pathways.",Language:"Language learning across IB programmes, with programme- and course-specific pathways in later years."}, native:"IB programme" },
    { id:"kumon", name:"Kumon Canada", short:"K", kind:"curriculum", badge:"Supplemental program", color:"red", range:"Ability-based", default:true, url:"https://www.kumon.com/ca-en", summary:{Math:"An individualized, worksheet-based progression that advances by demonstrated ability rather than school grade.",Language:"An individualized reading progression focused on comprehension and independent learning rather than school grade."}, native:"Kumon level" },
    { id:"bvg", name:"Bayview Glen", short:"BG", kind:"school", badge:"Independent school", color:"gold", range:"Preschool–12", default:true, url:"https://www.bayviewglen.ca/schools/lower-school/curriculum/", summary:{Math:"A school-specific implementation spanning foundational numeracy through secondary pathways, enriched by inquiry and application.",Language:"A school-specific literacy pathway emphasizing communication, reading, writing, and inquiry across divisions."}, native:"School grade" },
    { id:"tfs", name:"TFS — Canada's International School", short:"TFS", kind:"school", badge:"Independent school", color:"orange", range:"PK–12", url:"https://www.tfs.ca/academic-program", summary:{Math:"A bilingual, internationally oriented school pathway with programme-specific learning across divisions.",Language:"French and English language learning is central to the school's bilingual academic program."}, native:"School grade" },
    { id:"havergal", name:"Havergal College", short:"HC", kind:"school", badge:"Independent school", color:"green", range:"JK–12", url:"https://www.havergal.on.ca/academics/", summary:{Math:"A school-developed JK–12 academic pathway grounded in Ontario expectations and enriched through school programming.",Language:"A school-developed literacy pathway grounded in Ontario expectations and enriched through school programming."}, native:"School grade" },
    { id:"ucc", name:"Upper Canada College", short:"UCC", kind:"school", badge:"Independent school", color:"blue", range:"SK–12", url:"https://www.ucc.on.ca/learning", summary:{Math:"An inquiry-oriented pathway delivered within the school's programme structure.",Language:"Communication and literature learning delivered within the school's programme structure."}, native:"School grade" },
    { id:"branksome", name:"Branksome Hall", short:"BH", kind:"school", badge:"Independent school", color:"navy", range:"JK–12", url:"https://www.branksome.on.ca/academics", summary:{Math:"Mathematics delivered through the school's continuum of academic programming.",Language:"Language and literature delivered through the school's continuum of academic programming."}, native:"School grade" },
    { id:"bss", name:"The Bishop Strachan School", short:"BSS", kind:"school", badge:"Independent school", color:"red", range:"JK–12", url:"https://www.bss.on.ca/academics", summary:{Math:"A school-specific mathematics pathway across Junior, Middle, and Senior School.",Language:"A school-specific language pathway across Junior, Middle, and Senior School."}, native:"School grade" },
    { id:"crescent", name:"Crescent School", short:"CS", kind:"school", badge:"Independent school", color:"orange", range:"3–12", url:"https://www.crescentschool.org/academics", summary:{Math:"A school-specific mathematics pathway beginning in Grade 3.",Language:"A school-specific language pathway beginning in Grade 3."}, native:"School grade", minimumGrade:3 },
    { id:"stmichaels", name:"St. Michael's College School", short:"SMCS", kind:"school", badge:"Independent school", color:"gold", range:"7–12", url:"https://www.stmichaelscollegeschool.com/academics", summary:{Math:"A secondary mathematics pathway beginning in Grade 7.",Language:"A secondary English and language pathway beginning in Grade 7."}, native:"School grade", minimumGrade:7 }
  ]
};
