"use client";
import { useEffect,useMemo,useState } from "react";import type { CurriculumExpectation,GradeLevel,School,Source,Subject } from "@/lib/schema";import { gradeLevels } from "@/lib/schema";import { DEFAULT_SCHOOLS,parseState,serializeState } from "@/lib/url-state";
export function Comparison({schools,expectations,sources}:{schools:School[];expectations:CurriculumExpectation[];sources:Source[]}){const available=schools.filter(s=>s.reviewed);const initial=typeof window==="undefined"?{subject:"math" as Subject,schools:DEFAULT_SCHOOLS,grade:"1"}:parseState(new URLSearchParams(location.search),available.map(s=>s.id));const [subject,setSubject]=useState<Subject>(initial.subject);const [selected,setSelected]=useState(initial.schools);const [grade,setGrade]=useState(initial.grade as GradeLevel);const [open,setOpen]=useState<string|null>(null);
 useEffect(()=>{history.replaceState(null,"",serializeState({subject,schools:selected,grade}));},[subject,selected,grade]);
 const columns=available.filter(s=>selected.includes(s.id));const sourceMap=useMemo(()=>new Map(sources.map(s=>[s.id,s])),[sources]);
 function toggle(id:string){setSelected(current=>current.includes(id)?(current.length>1?current.filter(v=>v!==id):current):[...current,id]);}
 return <section aria-labelledby="comparison-title"><div className="controls"><label>Subject <select aria-label="Subject" value={subject} onChange={e=>{setSubject(e.target.value as Subject);setOpen(null)}}><option value="math">Mathematics</option><option value="language">Language</option></select></label><fieldset><legend>Schools and programs</legend>{available.map(s=><label key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={()=>toggle(s.id)}/>{s.shortName}</label>)}</fieldset></div>
 <div className="grades" aria-label="Grade progression">{gradeLevels.map(g=><button key={g} aria-pressed={grade===g} onClick={()=>{setGrade(g);setOpen(null)}}>{g}</button>)}</div>
 <h2 id="comparison-title">Grade {grade} · {subject==="math"?"Mathematics":"Language"}</h2><p className="hint">Select a card for evidence and qualification details.</p>
 <div className="comparison-grid" role="list">{columns.map(s=>{const item=expectations.find(e=>e.schoolId===s.id&&e.subject===subject&&e.grade===grade);const source=item?sourceMap.get(item.sourceId):undefined;const active=open===s.id;return <article role="listitem" className="card" key={s.id}><div className="card-head"><span className="school-type">{s.type.replaceAll("-"," ")}</span><h3>{s.shortName}</h3></div>{item?<><p className="strand">{item.comparisonLabel}</p><p>{item.expectation}</p><button className="details-button" aria-expanded={active} aria-controls={`detail-${s.id}`} onClick={()=>setOpen(active?null:s.id)}>{active?"Hide details":"View details"}</button>{active&&<div className="details" id={`detail-${s.id}`}><dl><dt>Published strand/domain</dt><dd>{item.strand}</dd><dt>Source wording</dt><dd>{item.sourceText}</dd><dt>Status</dt><dd>{item.verificationStatus.replaceAll("-"," ")}</dd><dt>Last reviewed</dt><dd>{item.lastReviewed}</dd></dl>{item.qualificationNotes&&<p><strong>Qualification:</strong> {item.qualificationNotes}</p>}{source&&<p><strong>Source:</strong> <a href={source.canonicalUrl} target="_blank" rel="noreferrer">{source.pageTitle} — {source.publisher}</a> <span className="source-kind">{source.kind.replaceAll("-"," ")}</span></p>}<a href="/contribute">Report a correction</a></div>}</>:<><p className="empty">Not publicly documented</p><p>No reviewed {subject} expectation is available for this grade.</p></>}</article>})}</div></section>}
